# Generated by Django 4.2.11 on 2024-10-31 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import random_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('random_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_numbers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='number',
            name='gen_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.IntegerField(default=random_app.models.gen_random_number),
        ),
    ]
